name: Velora FE CI/CD - WIF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: project-b67cf636-83ab-4f77-804
  SERVICE_NAME: velora-application
  REGION: asia-southeast1
  BACKEND_URL: https://api-service-318444823596.asia-southeast1.run.app

  AR_HOST: gcr.io
  AR_REPO: ''
permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: üì• Checkout Repository
        uses: actions/checkout@v4

      - name: üîê Authenticate Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/318444823596/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: velora@project-b67cf636-83ab-4f77-804.iam.gserviceaccount.com

      - name: ‚öôÔ∏è Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: üîë Authenticate Docker with Access Token
        run: |
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          echo $ACCESS_TOKEN | docker login -u oauth2accesstoken --password-stdin https://${{ env.AR_HOST }}

      - name: üì¶ Build Docker Image'
        run: |
          export IMAGE_URI="${{ env.AR_HOST }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"

           echo "Building image: $IMAGE_URI"

           docker build . \
             --tag $IMAGE_URI \
             --build-arg AUTH_SECRET_KEY="${{ secrets.AUTH_SECRET_KEY }}" \
             --build-arg NEXT_PUBLIC_APP_URL="https://velora-application-318444823596.asia-southeast1.run.app/" \
             --build-arg NEXT_PUBLIC_BACKEND_URL="${{ env.BACKEND_URL }}" \
             --build-arg NEXT_PUBLIC_BASEPATH="/home"

      - name: üö¢ Push Docker Image
        run: |
          docker push ${{ env.AR_HOST }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: üöÄ Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.AR_HOST }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          flags: --allow-unauthenticated
          env_vars: |
            NEXT_PUBLIC_BACKEND_URL=${{ env.BACKEND_URL }}
